### ISSUE TITLE
[bug] EIP authors should be tagged for EIP-1 related changes

### ISSUE THREAD

**Issue by poojaranjan** [ethereum/EIP-Bot#29]
The bot should tag EIP editors for EIP-1 related pull request.

<img width="928" alt="Screen Shot 2021-11-25 at 11 21 07 AM" src="https://user-images.githubusercontent.com/29681685/143475474-190ed4a4-ec0c-40f0-96a5-b4b6452ffb97.png">

Ref: https://github.com/ethereum/EIPs/pull/4498

**Comment by alita-moore** [comment]
@poojaranjan this is because the authors of eip-1 are not discernible. meaning they don't have a github handle except for their emails and it was a requested feature previously that they not be mentioned. There are a few options I can think of
1. show the names instead of email
2. replace their emails with their usernames we find
3. add an exception so that the emails show for eip-1

do any of these sound good? What new behvaior in particular would be best?

**Comment by MicahZoltu** [comment]
My preference would be to mention all EIP editors when there are changes to EIP-1 (special case).

**Comment by alita-moore** [comment]
This is done
