### ISSUE TITLE
[bug] No merge on approval.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/EIP-Bot#38]
https://github.com/ethereum/EIPs/pull/4361

The PR was approved by lightclient, but when CI re-runs (forced by closing and opening the issue) it still claims that it needs a review from lightclient or axic.

**Comment by alita-moore** [comment]
this is the same problem as https://github.com/ethereum/EIP-Bot/issues/35

**Comment by alita-moore** [comment]
I was mistaken, #35 is not the same issue.

**Comment by alita-moore** [comment]
fix was shipped here: https://github.com/ethereum/EIPs/commit/f563aab11e4d918d17d1d627de268e8360e8d347
implemented here: https://github.com/ethereum/EIP-Bot/commit/e3dbec627f8c7a5bdc33ca19970e5f9c4af9b626

The bug here was a result of the fact that github limits the number of responses it can return. At the time of this pull request the max number of reviews that could be returned was 30. But there were closer to 60 on the pull request. So when the bot requested reviews, it got back a truncated list that lacked the editor's approval. To fix this I built in a mechanism to get all reviews (no matter how many) and I increased the max to 100.

I also added integration tests for the PR in question.
