### ISSUE TITLE
Cannot delete files

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIP-Bot#63]
Deleting files ~~in the assets folder~~ anywhere causes EIP-bot to throw with a "not found" message, resulting in the PR failing to merge.

**Comment by Pandapip1** [comment]
This is now blocking two PRs: ethereum/EIPs#5054 and ethereum/EIPs#5017

**Comment by JEAlfonsoP** [comment]
Any particular reason why has been this "reopened" ?

**Comment by Pandapip1** [comment]
The fix apparently didn't work.

**Comment by JEAlfonsoP** [comment]
That fix as you mentioned, was addressed in EIPW ? (Question)

**Comment by Pandapip1** [comment]
No, it wasn't.

**Comment by JEAlfonsoP** [comment]
Deleting EIP asset file == modifying EIP asset files ? (Question), if this is the case then it would be covered with Issue 
#95.

**Comment by Pandapip1** [comment]
No, this is different. If any file is deleted, EIP-bot throws

**Comment by JEAlfonsoP** [comment]
is anyone working on it ?

**Comment by Pandapip1** [comment]
No, there is not.

**Comment by JEAlfonsoP** [comment]
I will take a look on it.

**Comment by SamWilsn** [comment]
I'm not looking at this one.

**Comment by JEAlfonsoP** [comment]
Hi.
I did several tests and PRs in the testing environment for this.

1. There is no bug with any of the bots: EIP-Bot and EIPW.
The test: https://github.com/JEAlfonsoP/EIPs/actions/runs/3093930099/jobs/5006818557
EIPW fails because the file pretending to be merged into the EIP repo does not follow EIP-1 rules. e.g:
Error: error: first line must be `---` exactly
 --> EIPS/eip-5255.md
  |
1 | Delete EIP-5000
  |

This is the first line for: https://github.com/ethereum/EIPs/pull/5255/commits/bdaf424ed9c178d462cc4c3ba71c3b6812bb2b89

2. Try to merge and delete an EIP: (Please I just try to delete last EIP-merged)
https://github.com/JEAlfonsoP/EIPs/pull/16
Actions: https://github.com/JEAlfonsoP/EIPs/actions/runs/3098269137 (No failure for any BOT).
There is a failure from CI: https://github.com/JEAlfonsoP/EIPs/actions/runs/3098269137/jobs/5015970668 (CodeSpell due to the fact that this empty case is not considered). 

Sam, may be the messages from EIPW could be a more explicative (a suggestion).
PandaPip1,  I presume that this empty check might be included in CI. 
General Observation: Any file to be merged must follows EIP1 rules.

Beside this I think that the case for deleting any file from the EIPs repo is solved. 

Let me know if  you need something else or if it's Ok so this issue could be closed.

**Comment by Pandapip1** [comment]
Your particular test didn't work because of an API rate limit: https://github.com/JEAlfonsoP/EIPs/actions/runs/3098245342/jobs/5015914203

**Comment by JEAlfonsoP** [comment]
> Your particular test didn't work because of an API rate limit: https://github.com/JEAlfonsoP/EIPs/actions/runs/3098245342/jobs/5015914203

? What is this Panda ?
I do not understand it.

**Comment by Pandapip1** [comment]
I am stating, as a fact, that deleting ***any*** file incorrectly throws a "not found" error due to the github API giving a 404 error. ***This is a bug, and is separate from any other CI elements correctly failing.***

**Comment by Pandapip1** [comment]
> You need to consider the fact that deleting an EIP's repo file does not activate EIP-Bot.

Yes, it does.

**Comment by JEAlfonsoP** [comment]
> > You need to consider the fact that deleting an EIP's repo file does not activate EIP-Bot.
> 
> 
> 
> Yes, it does.

Interesting. If you have a test case with the actual ./workflow please share it if you like, so I can take a look on it. 
Regardless, please, I ask you again that you advice if:
a.- You are working on this issue or any other one from this repo. So I avoid time consumption on it. 

Thank you !
