### ISSUE TITLE
Warn on spelling errors

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIP-Bot#72]
_Originally from #55_

It would be nice if the bot commented on PRs that contain a spelling error.

This shouldn't block merging, because jargon isn't always in the dictionary.

**Comment by JEAlfonsoP** [comment]
I will work on it.

**Comment by MicahZoltu** [comment]
Surprisingly, I have only had to override the spell checker once I think in all of my time as an editor.

**Comment by JEAlfonsoP** [comment]
As this action would not block merging: 
proposed action would be just remind authors to perform spell-checking right before merging.

**Comment by MicahZoltu** [comment]
We already have a spellchecker, it just lives in the old bot so failures only show up in Travis, which does block the build.  I think the idea with this issue is to have the bot somehow extract the spelling errors from Travis and turn them into individual comments (ideally suggestions) on the PR so the author can easily fix them without having to dig into CI.

**Comment by SamWilsn** [comment]
> the idea with this issue is to have the bot somehow extract the spelling errors from Travis and turn them into individual comments [...]

Exactly!

**Comment by MicahZoltu** [comment]
This now happens by moving to a codespell action, though I'm not a fan of how the suggestions are surfaced.
